[CmdletBinding()]
param(
    [string]$LlmHost,
    [string[]]$McpHosts = @(),
    [string[]]$WebHosts = @(),
    [switch]$AllowUntrustedStdio,
    [string[]]$AutoApproveTools = @(),
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Dieses Skript muss in einer PowerShell mit Administratorrechten ausgefuehrt werden."
}

$targetDirectory = Join-Path $env:ProgramData "cli-agent"
$targetFile = Join-Path $targetDirectory "admin_config.toml"

if ((Test-Path $targetFile) -and -not $Force) {
    Write-Host "Es existiert bereits eine Admin-Policy: $targetFile"
    Write-Host "Vorhandener Inhalt:"
    Get-Content $targetFile | ForEach-Object { Write-Host $_ }
    $answer = Read-Host "Policy vollstaendig ersetzen? [j/N]"
    if ($answer.ToLowerInvariant() -notin @("j", "ja", "y", "yes")) {
        Write-Host "Abgebrochen."
        exit 0
    }
}

function Normalize-Hosts([string[]]$Hosts, [switch]$IncludeLocal) {
    $values = @()
    if ($IncludeLocal) {
        $values += @("localhost", "127.0.0.1", "::1")
    }
    foreach ($hostName in $Hosts) {
        if (-not [string]::IsNullOrWhiteSpace($hostName)) {
            $values += $hostName.Trim().TrimEnd(".").ToLowerInvariant()
        }
    }
    return @($values | Select-Object -Unique)
}

function Toml-String([string]$Value) {
    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

function Toml-Array([string[]]$Values) {
    return "[" + (($Values | ForEach-Object { Toml-String $_ }) -join ", ") + "]"
}

if ([string]::IsNullOrWhiteSpace($LlmHost)) {
    $LlmHost = Read-Host "Zusaetzlich erlaubter LLM-Host (leer = nur localhost)"
}

$modelHosts = Normalize-Hosts -Hosts @($LlmHost) -IncludeLocal
$mcpAllowedHosts = Normalize-Hosts -Hosts $McpHosts -IncludeLocal
$webAllowedHosts = Normalize-Hosts -Hosts $WebHosts
$autoApprove = @($AutoApproveTools | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | ForEach-Object { $_.Trim() } | Select-Object -Unique)
$stdioValue = if ($AllowUntrustedStdio) { "true" } else { "false" }

$content = @"
# cli-agent machine-wide security policy
# Generated by scripts/setup-admin-config.ps1.
# Changes to this file require administrator privileges and are security-relevant.

[network]
model_allowed_hosts = $(Toml-Array $modelHosts)
mcp_allowed_hosts = $(Toml-Array $mcpAllowedHosts)
web_allowed_hosts = $(Toml-Array $webAllowedHosts)

[mcp]
allow_untrusted_stdio = $stdioValue

[mcp.approval]
auto_approve_tools = $(Toml-Array $autoApprove)
"@

New-Item -ItemType Directory -Path $targetDirectory -Force | Out-Null
Set-Content -Path $targetFile -Value $content -Encoding utf8

# Protect the policy from non-elevated modification. SIDs avoid localized group names.
& icacls.exe $targetFile /inheritance:r | Out-Null
& icacls.exe $targetFile /grant:r '*S-1-5-32-544:(F)' '*S-1-5-18:(F)' '*S-1-5-32-545:(R)' | Out-Null
if ($LASTEXITCODE -ne 0) {
    throw "Die ACL fuer $targetFile konnte nicht gesetzt werden."
}

Write-Host "Admin-Policy geschrieben: $targetFile"
Write-Host "Normale Benutzer koennen die Datei lesen, aber nur mit erhoehten Rechten aendern."
