[CmdletBinding()]
param(
    [string]$LlmHost,
    [string[]]$McpHosts = @(),
    [string[]]$WebHosts = @(),
    [switch]$AllowUntrustedStdio,
    [string[]]$AutoApproveTools = @(),
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Dieses Skript muss in einer PowerShell mit Administratorrechten ausgefuehrt werden."
}

# Keep this path in sync with cli_agent.admin_config.default_admin_config_file().
# Do not derive it from PROGRAMDATA: process environment variables are
# user-controlled and must not select a machine-wide security-policy file.
$targetDirectory = "C:\ProgramData\cli-agent"
$targetFile = Join-Path $targetDirectory "admin_config.toml"

function Assert-NotReparsePoint([string]$Path, [string]$Description) {
    if (Test-Path -LiteralPath $Path) {
        $item = Get-Item -LiteralPath $Path -Force
        if (($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
            throw "$Description darf kein Reparse Point/Symlink sein: $Path"
        }
    }
}

Assert-NotReparsePoint -Path $targetDirectory -Description "Der Admin-Policy-Ordner"
Assert-NotReparsePoint -Path $targetFile -Description "Die Admin-Policy-Datei"

if ((Test-Path -LiteralPath $targetFile) -and -not $Force) {
    Write-Host "Es existiert bereits eine Admin-Policy: $targetFile"
    Write-Host "Vorhandener Inhalt:"
    Get-Content -LiteralPath $targetFile | ForEach-Object { Write-Host $_ }
    $answer = Read-Host "Policy vollstaendig ersetzen? [j/N]"
    if ($answer.ToLowerInvariant() -notin @("j", "ja", "y", "yes")) {
        Write-Host "Abgebrochen."
        exit 0
    }
}

function Normalize-Hosts([string[]]$Hosts, [switch]$IncludeLocal) {
    $values = @()
    if ($IncludeLocal) {
        $values += @("localhost", "127.0.0.1", "::1")
    }
    foreach ($hostName in @($Hosts)) {
        if (-not [string]::IsNullOrWhiteSpace($hostName)) {
            $values += $hostName.Trim().TrimEnd(".").ToLowerInvariant()
        }
    }
    return @($values | Select-Object -Unique)
}

function Toml-String([string]$Value) {
    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

function Toml-Array([AllowNull()][string[]]$Values) {
    $items = @($Values | Where-Object { $null -ne $_ -and $_ -ne "" })
    if ($items.Count -eq 0) {
        return "[]"
    }
    return "[" + (($items | ForEach-Object { Toml-String $_ }) -join ", ") + "]"
}

function Invoke-Icacls([string[]]$Arguments, [string]$Description) {
    & icacls.exe @Arguments | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "$Description konnte nicht gesetzt werden (icacls Exit-Code $LASTEXITCODE)."
    }
}

function Invoke-Takeown([string]$Path, [string]$Description) {
    & takeown.exe /F $Path /A | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "$Description konnte nicht uebernommen werden (takeown Exit-Code $LASTEXITCODE)."
    }
}

if ([string]::IsNullOrWhiteSpace($LlmHost)) {
    $LlmHost = Read-Host "Zusaetzlich erlaubter LLM-Host (leer = nur localhost)"
}

$modelHosts = @(Normalize-Hosts -Hosts @($LlmHost) -IncludeLocal)
$mcpAllowedHosts = @(Normalize-Hosts -Hosts $McpHosts -IncludeLocal)
$webAllowedHosts = @(Normalize-Hosts -Hosts $WebHosts)
$autoApprove = @($AutoApproveTools | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | ForEach-Object { $_.Trim() } | Select-Object -Unique)
$stdioValue = if ($AllowUntrustedStdio) { "true" } else { "false" }

$content = @"
# cli-agent machine-wide security policy
# Generated by scripts/setup-admin-config.ps1.
# Changes to this file require administrator privileges and are security-relevant.

[network]
model_allowed_hosts = $(Toml-Array $modelHosts)
mcp_allowed_hosts = $(Toml-Array $mcpAllowedHosts)
web_allowed_hosts = $(Toml-Array $webAllowedHosts)

[mcp]
allow_untrusted_stdio = $stdioValue

[mcp.approval]
auto_approve_tools = $(Toml-Array $autoApprove)
"@

New-Item -ItemType Directory -Path $targetDirectory -Force | Out-Null
Assert-NotReparsePoint -Path $targetDirectory -Description "Der Admin-Policy-Ordner"

# A normal user may have pre-created the directory with explicit ACEs for their
# own SID. Take ownership, reset the DACL to inherited defaults, then remove
# inheritance before granting only the intended principals. This prevents stale
# explicit ACEs from surviving the setup.
Invoke-Takeown -Path $targetDirectory -Description "Der Besitz von $targetDirectory"
Invoke-Icacls -Arguments @($targetDirectory, "/reset") -Description "Die ACL fuer $targetDirectory"
Invoke-Icacls -Arguments @($targetDirectory, "/inheritance:r") -Description "Die ACL-Vererbung fuer $targetDirectory"
Invoke-Icacls -Arguments @(
    $targetDirectory,
    "/grant:r",
    '*S-1-5-32-544:(OI)(CI)(F)',
    '*S-1-5-18:(OI)(CI)(F)',
    '*S-1-5-32-545:(OI)(CI)(RX)'
) -Description "Die ACL fuer $targetDirectory"

# Do not preserve a pre-existing file object or any explicit ACLs attached to
# it. After the directory is protected, remove the old file and create a new
# policy file under the trusted directory ACL.
if (Test-Path -LiteralPath $targetFile) {
    Assert-NotReparsePoint -Path $targetFile -Description "Die Admin-Policy-Datei"
    Remove-Item -LiteralPath $targetFile -Force
}

# .NET's UTF8Encoding(false) is UTF-8 without BOM on Windows PowerShell 5.1
# as well as modern PowerShell. tomllib expects a BOM-free UTF-8 TOML file.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($targetFile, $content, $utf8NoBom)

# Replace the inherited file ACL with the exact machine-policy ACL.
Invoke-Icacls -Arguments @($targetFile, "/inheritance:r") -Description "Die ACL-Vererbung fuer $targetFile"
Invoke-Icacls -Arguments @(
    $targetFile,
    "/grant:r",
    '*S-1-5-32-544:(F)',
    '*S-1-5-18:(F)',
    '*S-1-5-32-545:(R)'
) -Description "Die ACL fuer $targetFile"

Write-Host "Admin-Policy geschrieben: $targetFile"
Write-Host "Normale Benutzer koennen die Policy lesen, aber weder die Datei noch ihren Policy-Ordner ohne erhoehte Rechte veraendern."
